services:
  - type: web
    name: webcam-filter-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ACCESS_CODE
        sync: false
